
version: '2'

# ["bash", "-c", "tcpdump", "-v", "&" , "./assignment3", "${control_port_one}"]

services:
  router_one:
    build: ./router
    working_dir: /router/davidtow
    command: ["tcpdump"]
    volumes:
        - ../davidtow:/router/davidtow
    networks:
        router_net:
            ipv4_address: "${ip_one}"
    ports:
        - "${control_port_one}:${control_port_one}"
        - "${router_port_one}:${router_port_one}"
        - "${data_port_one}:${data_port_one}"


networks:
  router_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1